 ---                   SQL analysis                      ---
 
SELECT * FROM "Customer"
LIMIT 20;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) as total_revenue
FROM "Customer"
GROUP by gender ;

-- This will help to design better compaign to target customer

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

Select avg(purchase_amount) 
From "Customer"

select 
	customer_id, 
	purchase_amount 
	from "Customer" 
	where discount_applied = 'Yes' 
	and purchase_amount >= (select AVG(purchase_amount) from "Customer")




-- Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased,Round(AVG(review_rating ::numeric),2) as Avg_product_rating
from "Customer"
group by 1
order by 2 DESC
LIMIT 5;

-- ERROR:  function round(double precision, integer) does not exist
-- HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
-- Fixed !

-- Q4. Compare the average purchase amounts between Standard and Express shipping methods.

SELECT shipping_type,
Round(AVG(purchase_amount),2)
from "Customer"
where shipping_type in ('Standard','Express')
Group by shipping_type 


-- Q5. Do subscribed customers spend more?
-- Compare the average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
Count(customer_id) as total_customers,
Round(avg(Purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
From "Customer"
GROUP by 1
Order by 1,2 DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
Round(100* SUM(CASE When discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
From "Customer"
GROUP by 1
ORDER by 2 DESC
LIMIT 5 ;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of customers in each segment.
-- IMP Q , customer Segmentation
SELECT * FROM "Customer"

WITH Customer_type AS (
Select customer_id , previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN ' Returning'
	ELSE 'Loyal'
	END as Customer_segment
From "Customer"
)

SELECT Customer_segment, COUNT(*) as Number_of_Cust
FROM Customer_type
GROUP by Customer_segment

-- This data is mainly on custtomer so here Loyal customer is more


-- Q8. What are the top 3 most purchased products within each category?

With item_counts as (
Select category,"Customer".item_purchased,count(customer_id) as total_orders,
Row_number() over (partition by category order by count(customer_id) DESC ) as item_rank
From "Customer"
Group by category ,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
From item_counts
WHERE item_rank <=3;

-- Rank and dense rank will put blause and pant in rank one cuz same value ..so it missed the actual ranked(DESC) product

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
-- cus if loyal customer is not have sucribed yet ,so its bad for business

SELECT subscription_status ,
count(Customer_id) as repeat_buyers
FROM "Customer"
Where previous_purchases > 5   -- 1st filter this for next opr
Group by 1

-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
Sum(purchase_amount) as total_revenue
FROM "Customer"
GROUP by age_group
order by 2 DESC

